### ISSUE TITLE
nukleus:update option set to none fails

### ISSUE THREAD

**Issue by NicoletaOita** [reaktivity/k3po-nukleus-ext.java#22]
Steps to reproduce:
Unignore and run the test SimplexIT.shouldThrottleInitialOnlyClientSentDataUpdateNone added in [this PR](https://github.com/reaktivity/k3po-nukleus-ext.java/pull/20).

**Comment by NicoletaOita** [comment]
I've created a [PR](https://github.com/reaktivity/k3po-nukleus-ext.java/pull/25) for this issue, but I've noticed that the k3po-nukleus-extension repo was extensively changed since I've started to work on it. After merging the latest sources, the test failed, so I'll have to investigate more to see why this is happening now with the new updates.

**Comment by NicoletaOita** [comment]
I've updated the [PR](https://github.com/reaktivity/k3po-nukleus-ext.java/pull/25), it seems the test failed because of the way I solved the conflicts when merging. 
@dpwspoon Please review. The fix is to send reset when the "update" option is set to none and the size of the window is smaller than the bytes that could be read. I'm not sure at this part how to calculate the bytes that are at some point using the window (readableBytes is always 1).

**Comment by jfallows** [comment]
Determined that we do not need to resolve this.
