### ISSUE TITLE
read event can be delivered before connected event

### ISSUE THREAD

**Issue by jitsni** [reaktivity/k3po-nukleus-ext.java#4]
```
[target -> http2]	[0x00000000105535b2] BEGIN [0x0000000000000000] [0x0b63ba9f45cb1225]
[http2 -> target]	[0x00000000444bde6b] BEGIN [0x0000000000000929] [0x0b63ba9f45cb1225]
[target <- http2]	[0x00000000105535b2] WINDOW [8192]
[http2 <- target]	[0x00000000444bde6b] WINDOW [8192]
```

**Comment by jfallows** [comment]
The `connected` event in the k3po `nukleus` transport is being deferred for `duplex` transmission until...

* `BEGIN` received,
* `WINDOW` sent
* `BEGIN` sent
* `WINDOW` received

...allowing `source.window` and `target.window` to be observed after the `connected` event.

However, we do not actually need to observe the `source.window` and `target.window`, so there is no need to wait for the `WINDOW` frame to be received.

Recommend removing support for `read nukleus:source.window` and `read nukleus:target.window` and then deliver the `connected` event after only...
* `BEGIN` received
* `BEGIN` sent

This additionally supports scenarios where no `WINDOW` is needed by the sender when the sender needs only to send `BEGIN` directly followed by `END`, with no `DATA` frames in between.
